apiVersion: v1
kind: Service
metadata:
  name: drone
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "drone.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "drone.selectorLabels" . | nindent 4 }}
