apiVersion: apps/v1

#Qual tipo de objeto pretende criar.
kind: Deployment

#Dados que ajudam a identificar de forma única o objeto, incluindo uma string nome, UID e um namespace
metadata:
  name: wander-poc-uzi

#Que estado deseja para o objeto.
spec:
  selector:
    matchLabels:
      app: wander-poc-uzi
  replicas: 2 # diz ao deployment para executar 2 pods que correspondam ao modelo
  revisionHistoryLimit: 0 #quantos replicaset antigos deve ser mantidos
  template:
    metadata:
      labels:
        app: wander-poc-uzi
    spec:
      containers:
      - name: wander-poc-uzi
        imagePullPolicy: Always
        image: wanderms25/poc-wander:f2f288c
        ports:
        - containerPort: 80        